/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "var(--ink)",
        "ink-1": "var(--ink-1)",
        "ink-2": "var(--ink-2)",
        "ink-3": "var(--ink-3)",
        plate: "var(--plate)",
        "rule-1": "var(--rule-1)",
        "rule-2": "var(--rule-2)",
        "rule-3": "var(--rule-3)",
        "text-hi": "var(--text-hi)",
        "text-mid": "var(--text-mid)",
        "text-lo": "var(--text-lo)",
        accent: "var(--accent)",
        "accent-2": "var(--accent-2)",
        ok: "var(--ok)",
        warn: "var(--warn)",
        crit: "var(--crit)",
        bg: "var(--ink)",
        panel: "var(--ink-2)",
        "panel-2": "var(--ink-3)",
        hair: "var(--rule-2)",
        "hair-strong": "var(--rule-3)",
        fg: "var(--text-hi)",
        "fg-dim": "var(--text-mid)",
        signal: "var(--ok)",
        cool: "var(--n-edge)",
      },
      fontFamily: {
        sans: ["Newsreader Variable", "Newsreader", "Georgia", "serif"],
        serif: ["Newsreader Variable", "Newsreader", "Georgia", "serif"],
        mono: ["Commit Mono", "JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        d1: ["var(--d1)", { lineHeight: "1", letterSpacing: "-0.03em" }],
        d2: ["var(--d2)", { lineHeight: "1.05", letterSpacing: "-0.03em" }],
        d3: ["var(--d3)", { lineHeight: "1.1", letterSpacing: "-0.03em" }],
        t1: ["var(--t1)", { lineHeight: "28px", letterSpacing: "-0.01em" }],
        t2: ["var(--t2)", { lineHeight: "28px" }],
        t3: ["var(--t3)", { lineHeight: "24px" }],
        m1: ["var(--m1)", { lineHeight: "24px" }],
        m2: ["var(--m2)", { lineHeight: "20px", letterSpacing: "0.02em" }],
        m3: ["var(--m3)", { lineHeight: "16px", letterSpacing: "0.11em" }],
      },
      spacing: {
        2: "2px",
        4: "4px",
        8: "8px",
        12: "12px",
        16: "16px",
        24: "24px",
        32: "32px",
        40: "40px",
        48: "48px",
        64: "64px",
        96: "96px",
        128: "128px",
        192: "192px",
      },
      borderRadius: {
        none: "0",
        DEFAULT: "0",
        sm: "0",
        md: "0",
        lg: "0",
        full: "9999px",
      },
      maxWidth: {
        measure: "var(--measure)",
        "measure-46": "min(46ch, 100%)",
        "measure-34": "min(34ch, 100%)",
      },
      screens: {
        sm: "620px",
        md: "1000px",
        lg: "1000px",
        xl: "1280px",
        "2xl": "1600px",
      },
      transitionTimingFunction: {
        ease: "cubic-bezier(0.2, 0.7, 0.2, 1)",
        snap: "cubic-bezier(0.3, 0, 0.2, 1)",
      },
      boxShadow: {
        overlay: "0 16px 48px -8px rgba(0,0,0,0.72)",
      },
    },
  },
  plugins: [],
};
