/* Generated by scripts/gen-learn-manifest.mjs. Do not edit.
 *
 * Card titles, summaries and topic levels: everything the index page renders,
 * and none of the material itself. The bodies, diagrams and questions live in
 * one module per group and are fetched when a card is opened.
 */
import type { CardMeta } from "./types";

export const manifest: CardMeta[] = [
  {
    "id": "networking",
    "title": "Networking and the web",
    "summary": "What actually happens between a browser and your server, and where the time goes.",
    "track": "foundations",
    "group": "foundations",
    "topics": [
      {
        "id": "request-lifecycle",
        "title": "The life of a request",
        "level": "beginner"
      },
      {
        "id": "tcp-vs-udp",
        "title": "TCP and UDP",
        "level": "beginner"
      },
      {
        "id": "http-versions",
        "title": "HTTP/1.1, HTTP/2 and HTTP/3",
        "level": "intermediate"
      },
      {
        "id": "dns",
        "title": "DNS and why it hurts you",
        "level": "intermediate"
      },
      {
        "id": "cdn",
        "title": "CDNs and edge caching",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "data-structures",
    "title": "Data structures and complexity",
    "summary": "The handful that come up constantly, and how to talk about cost without hand-waving.",
    "track": "foundations",
    "group": "foundations",
    "topics": [
      {
        "id": "big-o",
        "title": "Big-O without the ritual",
        "level": "beginner"
      },
      {
        "id": "hash-maps",
        "title": "Hash maps and their worst case",
        "level": "beginner"
      },
      {
        "id": "trees-indexes",
        "title": "B-trees and why databases use them",
        "level": "intermediate"
      },
      {
        "id": "bloom-filters",
        "title": "Bloom filters",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "databases-basics",
    "title": "Databases and data modelling",
    "summary": "Transactions, indexes, normalisation, and choosing between relational and document stores.",
    "track": "foundations",
    "group": "foundations",
    "topics": [
      {
        "id": "acid",
        "title": "ACID, stated plainly",
        "level": "beginner"
      },
      {
        "id": "indexes",
        "title": "Indexes and their cost",
        "level": "beginner"
      },
      {
        "id": "normalisation",
        "title": "Normalisation and when to break it",
        "level": "intermediate"
      },
      {
        "id": "sql-vs-nosql",
        "title": "Relational or document",
        "level": "intermediate"
      },
      {
        "id": "connection-pooling",
        "title": "Connection pooling",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "concurrency",
    "title": "Concurrency and operating systems",
    "summary": "Threads, processes, async, and the bugs that only appear under load.",
    "track": "foundations",
    "group": "foundations",
    "topics": [
      {
        "id": "process-thread-async",
        "title": "Processes, threads and async",
        "level": "beginner"
      },
      {
        "id": "race-conditions",
        "title": "Race conditions and locks",
        "level": "intermediate"
      },
      {
        "id": "idempotency",
        "title": "Idempotency",
        "level": "intermediate"
      },
      {
        "id": "backpressure",
        "title": "Backpressure",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "caching",
    "title": "Caching and Redis",
    "summary": "Strategies, invalidation, TTLs, and what actually goes wrong at scale.",
    "track": "design",
    "group": "design",
    "topics": [
      {
        "id": "cache-strategies",
        "title": "Cache-aside, write-through, write-behind",
        "level": "beginner"
      },
      {
        "id": "invalidation",
        "title": "Invalidation: TTL, explicit, and versioned keys",
        "level": "intermediate"
      },
      {
        "id": "redis-structures",
        "title": "Redis beyond get and set",
        "level": "intermediate"
      },
      {
        "id": "cache-failures",
        "title": "Stampedes, avalanches and hot keys",
        "level": "advanced"
      },
      {
        "id": "what-not-to-cache",
        "title": "What not to cache",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "load-balancing",
    "title": "Load balancing and traffic",
    "summary": "Spreading requests, and what breaks when a node disappears.",
    "track": "design",
    "group": "design",
    "topics": [
      {
        "id": "lb-algorithms",
        "title": "Round robin, least connections, hashing",
        "level": "beginner"
      },
      {
        "id": "consistent-hashing",
        "title": "Consistent hashing",
        "level": "advanced"
      },
      {
        "id": "health-checks",
        "title": "Health checks and draining",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "queues",
    "title": "Queues and asynchronous work",
    "summary": "Decoupling, delivery guarantees, and the ordering problem nobody mentions.",
    "track": "design",
    "group": "design",
    "topics": [
      {
        "id": "why-queues",
        "title": "What a queue actually buys you",
        "level": "beginner"
      },
      {
        "id": "delivery-guarantees",
        "title": "At-most-once, at-least-once, exactly-once",
        "level": "intermediate"
      },
      {
        "id": "ordering",
        "title": "Ordering and partitions",
        "level": "advanced"
      },
      {
        "id": "dead-letter",
        "title": "Retries and dead letter queues",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "scaling-data",
    "title": "Replication, sharding and consistency",
    "summary": "Scaling past one database, and what you give up when you do.",
    "track": "design",
    "group": "design",
    "topics": [
      {
        "id": "read-replicas",
        "title": "Read replicas and replication lag",
        "level": "intermediate"
      },
      {
        "id": "sharding",
        "title": "Sharding and choosing a key",
        "level": "advanced"
      },
      {
        "id": "cap",
        "title": "CAP, stated usefully",
        "level": "intermediate"
      },
      {
        "id": "eventual-consistency",
        "title": "Eventual consistency in the interface",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "resilience",
    "title": "Rate limiting and resilience",
    "summary": "Timeouts, retries, breakers, limits and degradation: staying up when a dependency does not.",
    "track": "design",
    "group": "design",
    "topics": [
      {
        "id": "rate-limiting",
        "title": "Token bucket and sliding window",
        "level": "intermediate"
      },
      {
        "id": "timeouts",
        "title": "Timeouts and deadlines",
        "level": "intermediate"
      },
      {
        "id": "retries-backoff",
        "title": "Retries, backoff and jitter",
        "level": "intermediate"
      },
      {
        "id": "circuit-breakers",
        "title": "Circuit breakers and bulkheads",
        "level": "intermediate"
      },
      {
        "id": "graceful-degradation",
        "title": "Graceful degradation and load shedding",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "observability",
    "title": "Observability",
    "summary": "Knowing what is happening, and what to measure instead of averages.",
    "track": "design",
    "group": "design",
    "topics": [
      {
        "id": "logs-metrics-traces",
        "title": "Logs, metrics and traces",
        "level": "beginner"
      },
      {
        "id": "percentiles",
        "title": "Percentiles, not averages",
        "level": "intermediate"
      },
      {
        "id": "slo",
        "title": "SLIs, SLOs and error budgets",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "api-design",
    "title": "API design",
    "summary": "REST, GraphQL, gRPC, webhooks and versioning, and which problem each one actually solves.",
    "track": "design",
    "group": "design2",
    "topics": [
      {
        "id": "rest",
        "title": "REST and resource modelling",
        "level": "beginner"
      },
      {
        "id": "graphql",
        "title": "GraphQL and its costs",
        "level": "intermediate"
      },
      {
        "id": "grpc",
        "title": "gRPC and binary protocols",
        "level": "intermediate"
      },
      {
        "id": "webhooks",
        "title": "Webhooks and delivery",
        "level": "advanced"
      },
      {
        "id": "versioning",
        "title": "Versioning and breaking changes",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "realtime",
    "title": "Real-time and push",
    "summary": "WebSockets, SSE, polling and pub/sub, and how to scale a connection you keep open.",
    "track": "design",
    "group": "design2",
    "topics": [
      {
        "id": "push-options",
        "title": "Polling, long polling, SSE, WebSockets",
        "level": "beginner"
      },
      {
        "id": "scaling-connections",
        "title": "Scaling persistent connections",
        "level": "advanced"
      },
      {
        "id": "presence",
        "title": "Presence and typing indicators",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "search",
    "title": "Search and ranking",
    "summary": "Inverted indexes, relevance, and why your database LIKE query does not scale.",
    "track": "design",
    "group": "design2",
    "topics": [
      {
        "id": "inverted-index",
        "title": "The inverted index",
        "level": "intermediate"
      },
      {
        "id": "relevance",
        "title": "Relevance and ranking",
        "level": "advanced"
      },
      {
        "id": "search-sync",
        "title": "Keeping the index in sync",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "storage-media",
    "title": "Storage and media",
    "summary": "Object storage, uploads, and delivering video without paying for it twice.",
    "track": "design",
    "group": "design2",
    "topics": [
      {
        "id": "object-storage",
        "title": "Object storage versus databases and disks",
        "level": "beginner"
      },
      {
        "id": "presigned-uploads",
        "title": "Direct uploads with pre-signed URLs",
        "level": "intermediate"
      },
      {
        "id": "video-delivery",
        "title": "Video: transcoding and adaptive bitrate",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "identity",
    "title": "Identity, auth and security",
    "summary": "Sessions, tokens, OAuth, and the mistakes that become incidents.",
    "track": "design",
    "group": "design2",
    "topics": [
      {
        "id": "authn-authz",
        "title": "Authentication and authorisation",
        "level": "beginner"
      },
      {
        "id": "sessions-vs-jwt",
        "title": "Sessions or JWTs",
        "level": "intermediate"
      },
      {
        "id": "oauth",
        "title": "OAuth and OpenID Connect",
        "level": "advanced"
      },
      {
        "id": "secrets",
        "title": "Secrets and encryption",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "coordination",
    "title": "Coordination and distributed state",
    "summary": "Leader election, consensus, distributed transactions and unique ids.",
    "track": "design",
    "group": "design2",
    "topics": [
      {
        "id": "leader-election",
        "title": "Leader election",
        "level": "advanced"
      },
      {
        "id": "consensus",
        "title": "Consensus: Raft and Paxos",
        "level": "advanced"
      },
      {
        "id": "saga",
        "title": "Distributed transactions and sagas",
        "level": "advanced"
      },
      {
        "id": "unique-ids",
        "title": "Generating unique ids at scale",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "data-pipelines",
    "title": "Data pipelines and analytics",
    "summary": "Batch, streaming, OLTP versus OLAP, and getting data out without hurting production.",
    "track": "design",
    "group": "design2",
    "topics": [
      {
        "id": "oltp-olap",
        "title": "OLTP and OLAP",
        "level": "beginner"
      },
      {
        "id": "batch-vs-stream",
        "title": "Batch and streaming",
        "level": "intermediate"
      },
      {
        "id": "cdc",
        "title": "Change data capture",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "containers",
    "title": "Containers and orchestration",
    "summary": "Docker, Kubernetes, and an honest answer about when you need neither.",
    "track": "delivery",
    "group": "delivery",
    "topics": [
      {
        "id": "what-docker-solves",
        "title": "What Docker actually solves",
        "level": "beginner"
      },
      {
        "id": "docker-vs-k8s",
        "title": "Docker or Kubernetes, and why",
        "level": "intermediate"
      },
      {
        "id": "image-hygiene",
        "title": "Image size, layers and security",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "cicd",
    "title": "CI/CD and deployment",
    "summary": "Getting changes to production safely and often.",
    "track": "delivery",
    "group": "delivery",
    "topics": [
      {
        "id": "pipeline",
        "title": "What a pipeline should do",
        "level": "beginner"
      },
      {
        "id": "deploy-strategies",
        "title": "Blue-green, canary and rolling",
        "level": "intermediate"
      },
      {
        "id": "migrations",
        "title": "Database migrations without downtime",
        "level": "advanced"
      },
      {
        "id": "feature-flags",
        "title": "Feature flags",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "cloud",
    "title": "Cloud platforms and cost",
    "summary": "AWS, GCP and Azure, and right-sizing instead of over-engineering.",
    "track": "delivery",
    "group": "delivery",
    "topics": [
      {
        "id": "core-services",
        "title": "The core services, by concept",
        "level": "beginner"
      },
      {
        "id": "right-sizing",
        "title": "Right-sizing: build for the traffic you have",
        "level": "intermediate"
      },
      {
        "id": "cost-drivers",
        "title": "Where cloud bills actually come from",
        "level": "advanced"
      },
      {
        "id": "serverless",
        "title": "Serverless, containers or VMs",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "testing",
    "title": "Testing",
    "summary": "What to test, at which level, and why coverage is a poor target.",
    "track": "practice",
    "group": "practice",
    "topics": [
      {
        "id": "test-pyramid",
        "title": "The testing pyramid",
        "level": "beginner"
      },
      {
        "id": "coverage",
        "title": "Coverage and what it does not tell you",
        "level": "intermediate"
      },
      {
        "id": "flaky-tests",
        "title": "Flaky tests",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "engineering-models",
    "title": "How teams work",
    "summary": "Waterfall, agile, scrum, kanban, what each assumes and when it breaks.",
    "track": "practice",
    "group": "practice",
    "topics": [
      {
        "id": "waterfall",
        "title": "Waterfall",
        "level": "beginner"
      },
      {
        "id": "agile",
        "title": "Agile, scrum and kanban",
        "level": "beginner"
      },
      {
        "id": "code-review",
        "title": "Code review",
        "level": "intermediate"
      },
      {
        "id": "incidents",
        "title": "Incidents and blameless postmortems",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "code-quality",
    "title": "Design and code quality",
    "summary": "Patterns, coupling, and technical debt as a deliberate choice.",
    "track": "practice",
    "group": "practice",
    "topics": [
      {
        "id": "coupling",
        "title": "Coupling and cohesion",
        "level": "intermediate"
      },
      {
        "id": "premature-abstraction",
        "title": "Premature abstraction",
        "level": "advanced"
      },
      {
        "id": "tech-debt",
        "title": "Technical debt as a decision",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "netflix",
    "title": "Netflix",
    "summary": "Ten subsystems behind pressing play: encoding, delivery, licensing, failure, and the data that decides what you see.",
    "track": "case-study",
    "group": "caseStudies",
    "topics": [
      {
        "id": "netflix-ingest",
        "title": "Ingest: what arrives before any of this works",
        "level": "beginner"
      },
      {
        "id": "netflix-encoding",
        "title": "Per-title and per-shot encoding: the bitrate ladder",
        "level": "advanced"
      },
      {
        "id": "netflix-abr",
        "title": "Adaptive bitrate: the decision the client makes every few seconds",
        "level": "intermediate"
      },
      {
        "id": "netflix-drm",
        "title": "DRM: three ecosystems, one encrypted file",
        "level": "advanced"
      },
      {
        "id": "netflix-cdn",
        "title": "Open Connect: building the CDN rather than buying it",
        "level": "intermediate"
      },
      {
        "id": "netflix-steering",
        "title": "Steering: choosing which appliance you talk to",
        "level": "advanced"
      },
      {
        "id": "netflix-microservices",
        "title": "Microservices and the compounding failure problem",
        "level": "advanced"
      },
      {
        "id": "netflix-caching",
        "title": "EVCache: caching across regions without distributed transactions",
        "level": "advanced"
      },
      {
        "id": "netflix-regions",
        "title": "Active-active regions and practising the evacuation",
        "level": "advanced"
      },
      {
        "id": "netflix-data",
        "title": "Personalisation and the data platform underneath it",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "uber",
    "title": "Uber",
    "summary": "Matching riders to drivers over real geography: indexing the world, dispatching against it, and keeping the money correct.",
    "track": "case-study",
    "group": "caseStudies",
    "topics": [
      {
        "id": "uber-geo",
        "title": "H3: why the world is tiled in hexagons",
        "level": "intermediate"
      },
      {
        "id": "uber-dispatch",
        "title": "Dispatch: matching is an assignment problem, not a search",
        "level": "advanced"
      },
      {
        "id": "uber-surge",
        "title": "Surge: a control loop that people can see",
        "level": "intermediate"
      },
      {
        "id": "uber-trip-state",
        "title": "The trip as a state machine, and why that matters",
        "level": "advanced"
      },
      {
        "id": "uber-sharding",
        "title": "Sharding by city, and what breaks at the edges",
        "level": "advanced"
      },
      {
        "id": "uber-payments",
        "title": "Payments: money is the part you cannot retry casually",
        "level": "advanced"
      },
      {
        "id": "uber-realtime",
        "title": "Keeping millions of connections open",
        "level": "intermediate"
      },
      {
        "id": "uber-data",
        "title": "The data platform: the same events, twice",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "twitter-feed",
    "title": "Twitter and the feed",
    "summary": "Fan-out on write against read, the celebrity problem, ranking, and the graph underneath it all.",
    "track": "case-study",
    "group": "caseStudies",
    "topics": [
      {
        "id": "fanout",
        "title": "Fan-out on write against fan-out on read",
        "level": "intermediate"
      },
      {
        "id": "celebrity-problem",
        "title": "The celebrity problem, and the hybrid that solves it",
        "level": "advanced"
      },
      {
        "id": "timeline-ranking",
        "title": "Ranking: when the timeline stops being chronological",
        "level": "advanced"
      },
      {
        "id": "social-graph",
        "title": "The follower graph, and why it is not just a table",
        "level": "intermediate"
      },
      {
        "id": "twitter-search",
        "title": "Search and trends: a different index over the same firehose",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "whatsapp",
    "title": "WhatsApp",
    "summary": "Delivery, ordering and encryption at billions of messages, with a server that is deliberately not allowed to read them.",
    "track": "case-study",
    "group": "caseStudies",
    "topics": [
      {
        "id": "whatsapp-connections",
        "title": "A process per connection, and why Erlang",
        "level": "advanced"
      },
      {
        "id": "chat-delivery",
        "title": "Delivery: the ticks, and what each one actually promises",
        "level": "intermediate"
      },
      {
        "id": "e2e",
        "title": "End-to-end encryption, and designing so the server cannot help",
        "level": "advanced"
      },
      {
        "id": "whatsapp-media",
        "title": "Media: the message is not the file",
        "level": "intermediate"
      },
      {
        "id": "whatsapp-groups",
        "title": "Groups: where the costs stop being linear",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "classic-designs",
    "title": "The classic designs",
    "summary": "URL shortener, rate limiter, ticket booking, file sync, distributed cache, notifications. The six that come up most.",
    "track": "case-study",
    "group": "caseStudies",
    "topics": [
      {
        "id": "url-shortener",
        "title": "URL shortener: the interview question that is actually about ids",
        "level": "beginner"
      },
      {
        "id": "rate-limiter",
        "title": "Rate limiter: four algorithms and the one you should reach for",
        "level": "intermediate"
      },
      {
        "id": "ticket-booking",
        "title": "Ticket booking: the seat that two people want",
        "level": "advanced"
      },
      {
        "id": "file-sync",
        "title": "File sync: conflicts are not an edge case",
        "level": "advanced"
      },
      {
        "id": "distributed-cache",
        "title": "Distributed cache: hashing, stampedes and the hot key",
        "level": "advanced"
      },
      {
        "id": "notifications",
        "title": "Notifications: fan-out with a person on the other end",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "sd-interview",
    "title": "The system design interview",
    "summary": "A structure that works, and what is actually being assessed.",
    "track": "interview",
    "group": "interview",
    "topics": [
      {
        "id": "framework",
        "title": "A structure for the 45 minutes",
        "level": "beginner"
      },
      {
        "id": "estimation",
        "title": "Back-of-envelope estimation",
        "level": "intermediate"
      },
      {
        "id": "tradeoffs",
        "title": "Talking about tradeoffs",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "seniority",
    "title": "Senior and staff signals",
    "summary": "What separates the levels, and how it shows up in interviews.",
    "track": "interview",
    "group": "interview",
    "topics": [
      {
        "id": "senior-vs-staff",
        "title": "Senior versus staff",
        "level": "advanced"
      },
      {
        "id": "behavioural",
        "title": "Behavioural answers with substance",
        "level": "intermediate"
      },
      {
        "id": "coding-round",
        "title": "The coding round",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "company-questions",
    "title": "Questions companies actually ask",
    "summary": "The recurring set across Google, Meta, Amazon, Microsoft, Uber, Stripe and the rest.",
    "track": "interview",
    "group": "companies",
    "topics": [
      {
        "id": "the-common-pool",
        "title": "The same thirty questions",
        "level": "beginner"
      },
      {
        "id": "by-company",
        "title": "What each company tends to press on",
        "level": "intermediate"
      },
      {
        "id": "cost-and-ops",
        "title": "Cost and operations are part of the answer",
        "level": "advanced"
      },
      {
        "id": "practice-plan",
        "title": "A practice plan that works",
        "level": "intermediate"
      }
    ]
  },
  {
    "id": "appsec",
    "title": "Application security",
    "summary": "Injection, XSS, CSRF, SSRF, the failures that turn a bug into a breach.",
    "track": "practice",
    "group": "security",
    "topics": [
      {
        "id": "sql-injection",
        "title": "Injection and parameterised queries",
        "level": "beginner"
      },
      {
        "id": "xss",
        "title": "Cross-site scripting",
        "level": "intermediate"
      },
      {
        "id": "csrf",
        "title": "CSRF and SameSite",
        "level": "intermediate"
      },
      {
        "id": "ssrf",
        "title": "SSRF and the metadata endpoint",
        "level": "advanced"
      },
      {
        "id": "supply-chain",
        "title": "Dependencies and supply chain",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "isolation",
    "title": "Transactions and isolation",
    "summary": "MVCC, snapshot isolation, write skew, and the anomalies your default level allows.",
    "track": "design",
    "group": "security",
    "topics": [
      {
        "id": "isolation-levels",
        "title": "The four levels and what each permits",
        "level": "intermediate"
      },
      {
        "id": "mvcc",
        "title": "MVCC and snapshot isolation",
        "level": "advanced"
      },
      {
        "id": "write-skew",
        "title": "Write skew",
        "level": "advanced"
      },
      {
        "id": "wal-outbox",
        "title": "The write-ahead log and the outbox",
        "level": "advanced"
      }
    ]
  },
  {
    "id": "replication-depth",
    "title": "Quorums, PACELC and failure domains",
    "summary": "Leaderless replication, the part of CAP nobody quotes, and containing blast radius.",
    "track": "design",
    "group": "security",
    "topics": [
      {
        "id": "quorums",
        "title": "Quorum reads and writes",
        "level": "advanced"
      },
      {
        "id": "pacelc",
        "title": "PACELC: the half of CAP nobody quotes",
        "level": "advanced"
      },
      {
        "id": "cells",
        "title": "Cells, bulkheads and blast radius",
        "level": "advanced"
      },
      {
        "id": "tail-at-scale",
        "title": "Tail latency: hedged requests and Little's Law",
        "level": "advanced"
      }
    ]
  }
];

export const topicCount = 145;
export const cardCount = 34;
