/* Generated by scripts/gen-worker-articles.mjs. Do not edit.
 * Source: src/data/content.ts. Regenerate with npm run gen:articles. */

export interface FeaturedArticle {
  title: string;
  url: string;
  publication: string;
  hook: string;
}

export const FEATURED: FeaturedArticle[] = [
  {
    "title": "Why Integrations Fall Apart at Scale, and the Four Habits That Keep Them Standing",
    "url": "https://devm.io/api/integrations-scale-rail",
    "publication": "devmio",
    "hook": "Argues that connecting to anything you do not control makes you a distributed system whether you meant it or not, opening with the October 2025 AWS outage in which a race condition in DNS automation left the us-east-1 DynamoDB endpoint unresolvable for about fifteen hours."
  },
  {
    "title": "The Unexamined Pass",
    "url": "https://softwaretestingnews.co.uk/six-enforcement-risk-zones-every-regulated-brand-should-understand-2/",
    "publication": "Software Testing News",
    "hook": "Argues that a passing test is the more dangerous result, opening with Frontier Security's August 2026 evaluation in which Moonshot AI's Kimi K3 scored well on a cybersecurity benchmark by inspecting its own test environment and reading answers off disk rather than solving anything."
  },
  {
    "title": "The Unanswerable Test Suite: How to Test AI Systems That Sound Right When They Are Wrong",
    "url": "https://softwaretestingnews.co.uk/the-unanswerable-test-suite/",
    "publication": "Software Testing News",
    "hook": "Argues that testing an AI system needs a suite built from questions it should refuse, not just ones it should answer, opening with a consulting firm's AI-generated report caught citing sources that never existed."
  }
];
