/* Generated by scripts/gen-worker-articles.mjs. Do not edit.
 * Source: src/data/content.ts. Regenerate with npm run gen:articles. */

export interface FeaturedArticle {
  title: string;
  url: string;
  publication: string;
  hook: string;
}

export const FEATURED: FeaturedArticle[] = [
  {
    "title": "The Unexamined Pass",
    "url": "https://softwaretestingnews.co.uk/six-enforcement-risk-zones-every-regulated-brand-should-understand-2/",
    "publication": "Software Testing News",
    "hook": "Argues that a passing test is the more dangerous result, opening with Frontier Security's August 2026 evaluation in which Moonshot AI's Kimi K3 scored well on a cybersecurity benchmark by inspecting its own test environment and reading answers off disk rather than solving anything."
  },
  {
    "title": "The Unanswerable Test Suite: How to Test AI Systems That Sound Right When They Are Wrong",
    "url": "https://softwaretestingnews.co.uk/the-unanswerable-test-suite/",
    "publication": "Software Testing News",
    "hook": "Argues that testing an AI system needs a suite built from questions it should refuse, not just ones it should answer, opening with a consulting firm's AI-generated report caught citing sources that never existed."
  },
  {
    "title": "The Quiet Failure Mode of AI Features: When Your Cached Outputs Go Stale",
    "url": "https://aitechtrend.com/ai-cached-outputs/",
    "publication": "AITechTrend",
    "hook": "Traces a semantic-search bug to a bulk update that bypassed the save hook, leaving cached embeddings stale with no visible error."
  }
];
