/* Generated by scripts/gen-worker-articles.mjs. Do not edit.
 * Source: src/data/content.ts. Regenerate with npm run gen:articles. */

export interface FeaturedArticle {
  title: string;
  url: string;
  publication: string;
  hook: string;
}

export const FEATURED: FeaturedArticle[] = [
  {
    "title": "The Unanswerable Test Suite: How to Test AI Systems That Sound Right When They Are Wrong",
    "url": "https://softwaretestingnews.co.uk/the-unanswerable-test-suite/",
    "publication": "Software Testing News",
    "hook": "Argues that testing an AI system needs a suite built from questions it should refuse, not just ones it should answer, opening with a consulting firm's AI-generated report caught citing sources that never existed."
  },
  {
    "title": "The Quiet Failure Mode of AI Features: When Your Cached Outputs Go Stale",
    "url": "https://aitechtrend.com/ai-cached-outputs/",
    "publication": "AITechTrend",
    "hook": "Traces a semantic-search bug to a bulk update that bypassed the save hook, leaving cached embeddings stale with no visible error."
  },
  {
    "title": "You Might Not Need a Hosted Embedding API",
    "url": "https://aitechtrend.com/embedding-api/",
    "publication": "AITechTrend",
    "hook": "Opens with the 2025 Shai-Hulud npm worm harvesting credentials straight out of build environments, to question why small corpora default to a hosted embedding API."
  }
];
